export const CREATE_APPOINTMENT = 'doctors-appointment-front-end/appointment/CREATE_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENTS';
export const ADD_DOCTOR = 'ADD_DOCTOR';
export const GET_DOCTORS = 'DOCTOR_APPOINTMENT/GET_DOCTORS';
export const CREATE_DOCTOR = 'DOCTOR_APPOINTMENT/CREATE_DOCTOR';
export const DELETE_DOCTOR = 'DOCTOR_APPOINTMENT/DELETE_DOCTOR';
export const RESET_APPOINTMENT = 'DOCTOR_APPOINTMENT/RESET_APPOINTMENT';
